DROP TABLE IF EXISTS to_dos CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE to_dos (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT Now(),
  completed_at TIMESTAMP DEFAULT NULL,
  category_id INTEGER REFERENCES categories(id)
);